apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: martino-todo

spec:
  type: NodePort

  selector:
    app: todo-app

  ports:
    - port: 8009
      targetPort: 8009
      nodePort: 30009
      protocol: TCP
